apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whatsapp-waha.fullname" . }}
  labels:
    {{- include "whatsapp-waha.labels" . | nindent 4 }}
  namespace: {{ include "whatsapp-waha.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "whatsapp-waha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "whatsapp-waha.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whatsapp-waha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "whatsapp-waha.fullname" . }}-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.persistence.sessions.enabled .Values.persistence.media.enabled }}
          volumeMounts:
            {{- if .Values.persistence.sessions.enabled }}
            - name: {{ include "whatsapp-waha.fullname" . }}-sessions
              mountPath: /app/.sessions
            {{- end }}
            {{- if .Values.persistence.media.enabled }}
            - name: {{ include "whatsapp-waha.fullname" . }}-media
              mountPath: /app/.media
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.persistence.sessions.enabled .Values.persistence.media.enabled }}
      volumes:
        {{- if .Values.persistence.sessions.enabled }}
        - name: {{ include "whatsapp-waha.fullname" . }}-sessions
          persistentVolumeClaim:
            claimName: {{ include "whatsapp-waha.fullname" . }}-sessions-pvc
        {{- end }}
        {{- if .Values.persistence.media.enabled }}
        - name: {{ include "whatsapp-waha.fullname" . }}-media
          persistentVolumeClaim:
            claimName: {{ include "whatsapp-waha.fullname" . }}-media-pvc
        {{- end }}
      {{- end }}
