apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "whatsapp-waha.fullname" . }}-sessions-pvc
  labels:
    {{- include "whatsapp-waha.labels" . | nindent 4 }}
  namespace: {{ include "whatsapp-waha.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.sessions.size }}
  {{- if .Values.persistence.sessions.storageClass }}
  {{- if (eq "-" .Values.persistence.sessions.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.sessions.storageClass }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "whatsapp-waha.fullname" . }}-media-pvc
  labels:
    {{- include "whatsapp-waha.labels" . | nindent 4 }}
  namespace: {{ include "whatsapp-waha.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.media.storageClass }}
  {{- if (eq "-" .Values.persistence.media.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.media.storageClass }}
  {{- end }}
  {{- end }}
