apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whatsapp-waha.fullname" . }}-env
  labels:
    {{- include "whatsapp-waha.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
