apiVersion: v1
data:
  SIDECAR_IMAGE: {{ .Values.sidecar.image | b64enc }}
kind: Secret
metadata:
  name: plugin-barman-cloud-{{ include "cloudnative-pg-barman-plugin.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudnative-pg-barman-plugin.labels" . | nindent 4 }}
type: Opaque