{{- if .Values.librechat.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "librechat.fullname" $ }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  librechat.yaml: |
{{ .Values.librechat.configYamlContent | toYaml | indent 4 }}

{{- end }}
